version: '3.1'
services:
  blog:
    image: hs/project/blog:0.0.4
    restart: always
    environment:
      GIN_MODE: "release"
    # volumes: 
    #   - ./conf/env.ini:/blog/env.ini
    ports:
      - 8000:8000