version: '3.1'
services:
  etcd:
    image: quay.io/coreos/etcd:v3.3.25
    restart: always
    environment:
      ETCD_NAME: test
      ETCD_DATA_DIR: /etcd-data
      ETCD_LISTEN_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_ADVERTISE_CLIENT_URLS: http://0.0.0.0:2379
      ETCD_LISTEN_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_ADVERTISE_PEER_URLS: http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER: test=http://0.0.0.0:2380
      ETCD_INITIAL_CLUSTER_TOKEN: test
      ETCD_INITIAL_CLUSTER_STATE: new
      ETCD_LOG_LEVEL: zap
      ETCD_LOG_OUTPUTS: stderr
    ports:
      - 2379:2379
      - 2380:2380